#encoding:utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Option.create(type_name:'method', code: 1, name:'직거래')
Option.create(type_name:'method', code: 2, name:'택배 거래')
Option.create(type_name:'method', code: 3, name:'상관 없음')

Option.create(type_name:'status', code: 1, name:'판매중')
Option.create(type_name:'status', code: 2, name:'거래 중')
Option.create(type_name:'status', code: 3, name:'판매 완료')

Option.create(type_name:'evaluation', code: 1, name:'good')
Option.create(type_name:'evaluation', code: 2, name:'bad')
Option.create(type_name:'evaluation', code: 3, name:'no')

uplevel=Category.create(name:"의류")
Category.create(name:"캐쥬얼상의", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"캐쥬얼하의", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"여성상의", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"여성하의", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"남성상의", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"남성하의", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"학생교복", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"파티/잠옷/작업복등", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"수입명품")
Category.create(name:"루이비통", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"샤넬", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"버버리/마크제이콥스", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"불가리/까르띠에", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"구찌/프라다", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"디올/입생로랑", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"에르메스/콜롬보", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"발리/에트로/페라가모", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 수입명품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"패션잡화")
Category.create(name:"여성신발", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"남성신발", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"가방/모자/장갑", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"지갑/벨트/시계", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"안경/선글라스", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"쥬얼리/악세사리", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 패션잡화", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"미용")
Category.create(name:"여성 기초화장품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"여성 색조화장품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"남성화장품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"향수/아로마", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"헤어/바디케어", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"요가/운동용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 미용", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"출산/유아")
Category.create(name:"출산/임부용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"유아/아동의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"유아/아동용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"인형/장난감", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"유아책/교육", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"모바일")
Category.create(name:"모바일 자유게시판", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"SKT", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"KTF", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"LGT", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타통신사/피처폰", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"주변기기/악세사리", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"컴퓨터")
Category.create(name:"컴퓨터 자유게시판", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"노트북/넷북", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"태블릿PC", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"데스크탑/본체", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"모니터 ", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"CPU/메인보드/HDD", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"메모리/VGA/ODD", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"케이스/키보드마우스", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"복합기/프린터", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"USB/케이블/스피커", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"허브/무선랜/공유기", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"잉크/토너/공CD", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"PC게임/소프트웨어", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 제품/PC파워", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"카메라")
Category.create(name:"카메라 자유게시판", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"DSLR ", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"미러리스", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"일반디카/하이엔드", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"필름/중형카메라", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"렌즈/필터/컨버터", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"삼각대/플래시/조명", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"메모리/배터리/가방", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 카메라악세사리", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"영상기기")
Category.create(name:"영상기기 자유게시판", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"디지털TV", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"DVD/VCR", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"PMP/DMB", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"셋톱박스/프로젝터", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"디지털 캠코더", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"편집기기/소프트웨어", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 영상관련제품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"음악/음향/악기")
Category.create(name:"음악음향 자유게시판", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"MP3/CDP", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"오디오/홈시어터", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"헤드폰/스피커/앰프", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 음향기기", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"LP/CD/DVD 음반", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"건반악기", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"관악기", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"현악기", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"타악기", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"게임용품")
Category.create(name:"게임 자유게시판", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"NDSL/WII/닌텐도", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"PSP/PS2/PS3", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"XBOX360", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"게임소프트웨어", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 게임용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"스포츠/취미")
Category.create(name:"축구용품/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"야구용품/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"농구용품/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"MTB사이클 용품의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"미니벨로/일반자전거", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"인라인/스케이트보드", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"스키/보드/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"골프용품/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"헬스/수영/용품/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"피규어/프라모델/브릭", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타스포츠/레져용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"여행")
Category.create(name:"등산용품/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"캠핑용품/장비", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"낚시용품/의류", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"여행시설 이용권", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"숙박권", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"생활용품")
Category.create(name:"사무용품 복사기팩스", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"대형가전(TV,냉장고,세탁기,에어컨 등)", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"소형가전(밥솥,다리미,가습기,면도기 등)", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"침구/커튼/패브릭", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"욕실용품/주방용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"전자사전/MC스퀘어", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"상품권/판매가능티켓", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"반려동물 용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"DIY/리폼 용품,공구", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"학습도구/문구", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 중고", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"가구")
Category.create(name:"침실(침대/화장대)", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"거실(쇼파/테이블)", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"주방(식탁/수납장)", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"사무용(책상/서랍)", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"인테리어소품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"예술/미술", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"서양/동양/현대작품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"미술재료/물감/마카", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"미술용품도구", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"골동품/기타수집", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"도서관련")
Category.create(name:"학습/사전/참고서", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"문학/과학/경영", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"월간/계간/잡지", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"여행/취미/레져", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"예술/디자인도서", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"컴퓨터/인터넷도서", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"아동/어린이도서", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"소설/만화책", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"전집", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"국산차/오토바이/용품")
Category.create(name:"차량 자유게시판", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"경차/소형차", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"준/중형차", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"준/대형차", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"스포츠카", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"SUV/RV", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"화물차/버스/승합차", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 차량", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"오토바이 125CC초과", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"오토바이 125CC이하", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"오토바이 용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"카오디오/DVD", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"차량용TV/네비", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"휠/타이어/캐리어", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 차량용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
uplevel=Category.create(name:"수입차")
Category.create(name:"BMW", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"벤츠", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"아우디", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"폭스바겐/링컨", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"볼보/푸조/JEEP", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"포드/크라이슬러", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"인피니티/렉서스", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"닛산/혼다/도요타", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"캐딜락/재규어", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"포르쉐/랜드로버", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"기타 수입차", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"산업용품", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"드릴/전동공구", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"에어/유압공구", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"측정/계측/레벨", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"공작기계/용접/가스", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"공구/공구함", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
Category.create(name:"산업용품/자재", uplevel_id:uplevel.id, uplevel_list:uplevel.name,count:0)
